language: python
cache: pip
sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

env:
  - DJANGO=<3
  - DJANGO=<4
  - DJANGO=<5

install:
  - pip install pipenv
  - pip install "django$DJANGO"
  - pipenv install --dev

matrix:
  fast_finish: true
  include:
    - python: 3.7
      sudo: true
dist: xenial

script: make coverage

after_success:
  - codecov
