language: python
cache: pip
sudo: false

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1

install:
  - pip install pipenv
  - pip install django==$DJANGO
  - pipenv install --dev

matrix:
    fast_finish: true

script: make coverage

after_success:
  - codecov
