# Config file for automatic testing at travis-ci.org

language: python

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pipenv install

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov
